initial_state = [
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
     True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
     True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
     True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
     True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
     True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
     True, True, True, True],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False],
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
     False, False, False, False]]
